---
- name: include os variables
  include_vars: "{{subversion_os}}.yml"
  when: subversion_os is defined and subversion_os != ""

################################################################################################

- name: install subversion
  apt: pkg={{subversion_package}} state=present update_cache=yes cache_valid_time=3600